config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root :to => 'projects#index'
	resources :projects do
		resources :bugs
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

	has_many :project_users, dependent: :destroy
	has_many :bugs,dependent: :destroy
	has_many :developers , through: :project_users
	belongs_to :manager,  class_name: "User",foreign_key: "manager_id"
	validates :title, presence: true
	validates :description, presence: true
	def getOnlyDevelopers
		developers.where(user_type: 'Developer').all
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
    load_and_authorize_resource
  def index
  	# Project.paginate(page: params[:page], per_page: 5)
    if current_user.user_type == 'Manager'
      @projects=current_user.managerprojects.paginate(page: params[:page], per_page: 5)
    else
      @projects=current_user.projects.paginate(page: params[:page], per_page: 5)
    end
  end

  def new
  	@project=Project.new
  	
  end
  def create
    @project = Project.new(project_params)
        
        @project.manager=current_user
		
        respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: root_path }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  def show
  	
	@participants=@project.developers
  	

  end
  def destroy
	@project.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def edit
    @users=User.where(user_type: 'Developer').all
    @users1=User.where(user_type: 'QA').all
    @users=@users+@users1
  end
  def update
          

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

   private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params

      params.require(:project).permit(:title, :description,:developer_ids => [])
    end

end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/projects/_form.html.erb
<%= render 'shared/errors', obj: @project %>



<div class='row'>

	<div class='col-xs-12'>

		<%= form_for(@project, :html => {class: "form-horizontal", role: "form"}) do |f| %>

			<div class="form-group">

				<div class="control-label col-sm-2">

				<%= f.label :title %>

				</div>

				<div class="col-sm-8">

				<%= f.text_field :title, class: "form-control", placeholder: "Title of Project", autofocus: true %>

				</div>

				</div>

				<div class="form-group">

				<div class="control-label col-sm-2">

				<%= f.label :description %>

				</div>

				<div class="col-sm-8">

				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Project" %>

				</div>
				
				</div>
				<div class="form-group">

					<div class="control-label col-sm-2">

						<%= f.label :users %>

					</div>
					<div class="col-sm-8">

				<%= f.collection_select(:developer_ids, User.returnUserDevelopers, :id, :name, {include_blank: true}, {multiple: true, class: "form-control"})  %>

					</div>

				</div>
				


				<div class="form-group">

				<div class="col-sm-offset-2 col-sm-10">

				<%= f.submit class: 'btn btn-primary btn-lg' %>

				</div>

			</div>

			<% end %>

			<div class="col-xs-4 col-xs-offset-4">

			[ <%= link_to "Go back to Welcome Page", root_path %> ]

		</div>

	</div>

</div>

app/views/projects/_messages.html.erb
<div class="row">

<div class="col-xs-10 col-xs-offset-1">

<% flash.each do |name, msg| %>

<div class='alert alert-<%="#{name}" %>'>

<a href="#" class="close" data-dismiss="alert">×</a>

<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>

</div>

<% end %>

</div>

</div>

app/views/projects/edit.html.erb
<h1 align="center">EditProject</h1>

<%= render 'form', post: @project %>

app/views/projects/index.html.erb
<h1 align="center">All Projects</h1>
<div align="center">
 <% if @projects.count == 0 %>
 <div>
	<p class="bg-info">Nothing to Show Here</p>
 </div>
 <% end %>
<%= will_paginate @projects %>

</div>


<% @projects.each do |project| %>

<div class="row" height:500px>

<div class="col-xs-8 col-xs-offset-2">

<div class="well well-lg">

<div class="project-title">

<%= link_to project.title, project_path(project) %>

</div>

<div class="project-body">

<%= truncate(project.description, length: 100) %>

</div>
<div align="left">
	<b>Created by: </b>
	<%= simple_format(project.manager.name) %>

</div>
	<% if can? :manage, project %>
		<div class="article-actions">
			
				<%= link_to "Edit this Project", edit_project_path(project), class: "btn btn-xs btn-primary" %>
			
				<%= link_to "Delete this Project", project_path(project), method: :delete,

				data: { confirm: "Are you sure you want to delete the project?"},

				class: "btn btn-xs btn-danger" %>

		</div>
	<% end %>
	
</div>

</div>

</div>


<% end %>
<div align="center">

<%= will_paginate @projects %>

</div>
</div>

app/views/projects/new.html.erb
<h1 align="center">New Project</h1>

<%= render 'form', post: @project %>

app/views/projects/show.html.erb
<h2 align="center">Project: <%= @project.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">

<h4 class="center description"><strong>Description:</strong></h4>

<hr>

<%= simple_format(@project.description) %>


<div align="center">
	<b>Created by: </b>
	<%= simple_format(@project.manager.name) %>

</div>
<div align="center">
<b  >Participants:</b>
	<% @participants.each do |participant| %>
      
      <p>
      	<%= participant.name+"     " +  participant.user_type  %>
      </p	

    <% end %>
</div>

<div class="form-group"></div>
<div class="project-actions">
<% if can? :manage, @project %>
<%= link_to "Edit this project", edit_project_path(@project), class: "btn btn-xs btn-primary" %>

<%= link_to "Delete this project", project_path(@project), method: :delete,

data: { confirm: "Are you sure you want to delete the article?"},

class: "btn btn-xs btn-danger" %>
<% end %>
<%= link_to "View all Projects", root_path, class: "btn btn-xs btn-success" %>


</div>
<div class="form-group"></div>
<div align="center">
<%= link_to "Create New Bug", new_project_bug_path(@project), class: "btn btn-lg btn-success" %>
</div>

</div>
</div>
<div class=" col-xs-10 col-xs-offset-1">
	<h3 align="center">Bugs related to Project</h3>
	<div align="center">
		 <% if @project.bugs.count == 0 %>
			 <div>
				<p class="bg-info">Nothing to Show Here</p>
			 </div>
		 <% end %>
	</div>
	<% @project.bugs.each do |bug| %>

	<div class="row">

		<div class="col-xs-8 col-xs-offset-2">

			<div class="well well-lg">

			<div class="project-title">

			<%= link_to bug.title, project_bug_path(@project,bug) %>

			</div>

			<div class="project-body">

			<%= truncate(bug.description, length: 100) %>

			</div>
			<div align="left">
				<b>Created by: </b>
				<%= bug.creator.name%>

			</div>
			<% if bug.developer %>
			<div align="left">
				<b>Developer: </b>
				<%= bug.developer.name %>

			</div>
			<% end %>
			<% if can? :manage, bug %>
					<div class="article-actions">
						
							<%= link_to "Edit this Bug", edit_project_bug_path(@project,bug), class: "btn btn-xs btn-primary" %>
						
							<%= link_to "Delete this Bug", project_bug_path(@project,bug), method: :delete,

							data: { confirm: "Are you sure you want to delete the Bug?"},

							class: "btn btn-xs btn-danger" %>

					</div>
				
			<% end%>	
			</div>

		</div>

	</div>

	<% end %>
</div>
</div>